version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  versioning-strategy: increase
  commit-message:
      prefix: deps
      prefix-development: deps-dev
