version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 30
  reviewers:
    - r4356th
  versioning-strategy: increase
  commit-message:
      prefix: deps
      prefix-development: deps-dev
